/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/layout/AdminLayout.vue')['default']
    Alert: typeof import('./src/components/common/dialog/Alert.vue')['default']
    BaseComponentMixin: typeof import('./src/components/BaseComponentMixin.vue')['default']
    Breadcrumb: typeof import('./src/components/layout/Breadcrumb.vue')['default']
    CollapseToggleButton: typeof import('./src/components/common/CollapseToggleButton.vue')['default']
    CommentForm: typeof import('./src/components/comment/CommentForm.vue')['default']
    CommentItem: typeof import('./src/components/comment/CommentItem.vue')['default']
    CommentList: typeof import('./src/components/comment/CommentList.vue')['default']
    CommentReplyTree: typeof import('./src/components/comment/CommentReplyTree.vue')['default']
    Confirm: typeof import('./src/components/common/dialog/Confirm.vue')['default']
    CookieTest: typeof import('./src/components/CookieTest.vue')['default']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    FriendshipLinks: typeof import('./src/components/FriendshipLinks.vue')['default']
    HeaderControls: typeof import('./src/components/theme/HeaderControls.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconPreview: typeof import('./src/components/common/IconPreview.vue')['default']
    IconSelector: typeof import('./src/components/common/IconSelector.vue')['default']
    IpLocationTag: typeof import('./src/components/common/IpLocationTag.vue')['default']
    MainUserStatistics: typeof import('./src/components/MainUserStatistics.vue')['default']
    Modal: typeof import('./src/components/common/dialog/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarCollapseSample: typeof import('./src/components/layout/SidebarCollapseSample.vue')['default']
    SystemConfig: typeof import('./src/components/admin/SystemConfig.vue')['default']
    Temp: typeof import('./src/components/layout/temp.vue')['default']
    ToggleIconButton: typeof import('./src/components/common/ToggleIconButton.vue')['default']
    UserStatistics: typeof import('./src/components/dashboard/UserStatistics.vue')['default']
    UserStatsDashboard: typeof import('./src/components/user/UserStatsDashboard.vue')['default']
    VisitorIdDisplay: typeof import('./src/components/common/VisitorIdDisplay.vue')['default']
  }
}
