<?php
// 多语言设置
return [
    // 默认语言
    'default_lang'    => env('lang.default_lang', 'zh-cn'),
    // 允许的语言列表
    'allow_lang_list' => ['zh-cn', 'en-us'],
    // 多语言自动侦测变量名
    'detect_var'      => 'lang',
    // 是否使用Cookie记录
    'use_cookie'      => true,
    // 多语言cookie变量
    'cookie_var'      => 'think_lang',
    // 多语言header变量
    'header_var'      => 'think-lang',
    // 扩展语言包
    'extend_list'     => [
        'en-us'=>[
            app()->getAppPath() . 'lang/en-us/admin.php',
            app()->getAppPath() . 'lang/en-us/api.php',
            app()->getAppPath() . 'lang/en-us/auth.php',
            app()->getAppPath() . 'lang/en-us/common.php',
            app()->getAppPath() . 'lang/en-us/lang.php',
            app()->getAppPath() . 'lang/en-us/test.php',
            app()->getAppPath() . 'lang/en-us/token.php',
            app()->getAppPath() . 'lang/en-us/user.php',
            app()->getAppPath() . 'lang/en-us/web.php',
            app()->getAppPath() . 'lang/en-us/blog.php',
            app()->getAppPath() . 'lang/en-us/link.php',
            app()->getAppPath() . 'lang/en-us/contact.php',
            app()->getAppPath() . 'lang/en-us/debug.php',
            app()->getAppPath() . 'lang/en-us/index.php',
            app()->getAppPath() . 'lang/en-us/ipLocation.php',
            app()->getAppPath() . 'lang/en-us/statistics.php',
            app()->getAppPath() . 'lang/en-us/adminComment.php',
            app()->getAppPath() . 'lang/en-us/adminCat.php',
            app()->getAppPath() . 'lang/en-us/adminTag.php',
            app()->getAppPath() . 'lang/en-us/adminArticle.php',
            app()->getAppPath() . 'lang/en-us/adminAiTool.php',
            app()->getAppPath() . 'lang/en-us/adminAiToolCategory.php',
            app()->getAppPath() . 'lang/en-us/adminAiToolTag.php',
            app()->getAppPath() . 'lang/en-us/adminAiToolComment.php',
            app()->getAppPath() . 'lang/en-us/adminAiToolFavorite.php',
            app()->getAppPath() . 'lang/en-us/adminIpLocation.php',
            app()->getAppPath() . 'lang/en-us/adminAiToolLike.php',
            app()->getAppPath() . 'lang/en-us/adminAiToolVisitLog.php',
            app()->getAppPath() . 'lang/en-us/adminAiToolCommentLike.php',
            app()->getAppPath() . 'lang/en-us/adminCommentLike.php',
            app()->getAppPath() . 'lang/en-us/adminContact.php',
            app()->getAppPath() . 'lang/en-us/adminFavorite.php',
            app()->getAppPath() . 'lang/en-us/adminLike.php',
            app()->getAppPath() . 'lang/en-us/adminLink.php',
            app()->getAppPath() . 'lang/en-us/adminPost.php',

            app()->getAppPath() . 'lang/en-us/aiTool.php',
            app()->getAppPath() . 'lang/en-us/aiToolCategory.php',
            app()->getAppPath() . 'lang/en-us/aiToolTag.php',
            app()->getAppPath() . 'lang/en-us/aiToolComment.php',
            app()->getAppPath() . 'lang/en-us/aiToolFavorite.php',
            app()->getAppPath() . 'lang/en-us/aiToolLike.php',
            app()->getAppPath() . 'lang/en-us/aiToolVisitLog.php',
            app()->getAppPath() . 'lang/en-us/aiToolCommentLike.php',

            app()->getAppPath() . 'lang/en-us/tool.php',
            app()->getAppPath() . 'lang/en-us/toolComment.php',
            app()->getAppPath() . 'lang/en-us/toolFavorite.php',
            app()->getAppPath() . 'lang/en-us/toolLike.php',
            app()->getAppPath() . 'lang/en-us/search.php',
            app()->getAppPath() . 'lang/en-us/comment.php',
            app()->getAppPath() . 'lang/en-us/commentLike.php',
            app()->getAppPath() . 'lang/en-us/favorite.php',
            app()->getAppPath() . 'lang/en-us/like.php',
            app()->getAppPath() . 'lang/en-us/post.php',
        ],
        'zh-cn'=>[
            app()->getAppPath() . 'lang/zh-cn/admin.php',
            app()->getAppPath() . 'lang/zh-cn/api.php',
            app()->getAppPath() . 'lang/zh-cn/auth.php',
            app()->getAppPath() . 'lang/zh-cn/common.php',
            app()->getAppPath() . 'lang/zh-cn/lang.php',
            app()->getAppPath() . 'lang/zh-cn/test.php',
            app()->getAppPath() . 'lang/zh-cn/token.php',
            app()->getAppPath() . 'lang/zh-cn/user.php',
            app()->getAppPath() . 'lang/zh-cn/web.php',
            app()->getAppPath() . 'lang/zh-cn/blog.php',
            app()->getAppPath() . 'lang/zh-cn/link.php',
            app()->getAppPath() . 'lang/zh-cn/contact.php',
            app()->getAppPath() . 'lang/zh-cn/debug.php',
            app()->getAppPath() . 'lang/zh-cn/index.php',
            app()->getAppPath() . 'lang/zh-cn/ipLocation.php',
            app()->getAppPath() . 'lang/zh-cn/statistics.php',
            app()->getAppPath() . 'lang/zh-cn/adminComment.php',
            app()->getAppPath() . 'lang/zh-cn/adminCat.php',
            app()->getAppPath() . 'lang/zh-cn/adminTag.php',
            app()->getAppPath() . 'lang/zh-cn/adminArticle.php',
            app()->getAppPath() . 'lang/zh-cn/adminAiTool.php',
            app()->getAppPath() . 'lang/zh-cn/adminAiToolCategory.php',
            app()->getAppPath() . 'lang/zh-cn/adminAiToolTag.php',
            app()->getAppPath() . 'lang/zh-cn/adminAiToolComment.php',
            app()->getAppPath() . 'lang/zh-cn/adminAiToolFavorite.php',
            app()->getAppPath() . 'lang/zh-cn/adminIpLocation.php',
            app()->getAppPath() . 'lang/zh-cn/adminAiToolLike.php',
            app()->getAppPath() . 'lang/zh-cn/adminAiToolVisitLog.php',
            app()->getAppPath() . 'lang/zh-cn/adminAiToolCommentLike.php',
            app()->getAppPath() . 'lang/zh-cn/adminCommentLike.php',
            app()->getAppPath() . 'lang/zh-cn/adminContact.php',
            app()->getAppPath() . 'lang/zh-cn/adminFavorite.php',
            app()->getAppPath() . 'lang/zh-cn/adminLike.php',
            app()->getAppPath() . 'lang/zh-cn/adminLink.php',
            app()->getAppPath() . 'lang/zh-cn/adminPost.php',

            app()->getAppPath() . 'lang/zh-cn/aiTool.php',
            app()->getAppPath() . 'lang/zh-cn/aiToolCategory.php',
            app()->getAppPath() . 'lang/zh-cn/aiToolTag.php',
            app()->getAppPath() . 'lang/zh-cn/aiToolComment.php',
            app()->getAppPath() . 'lang/zh-cn/aiToolFavorite.php',
            app()->getAppPath() . 'lang/zh-cn/aiToolLike.php',
            app()->getAppPath() . 'lang/zh-cn/aiToolCommentLike.php',

            app()->getAppPath() . 'lang/zh-cn/tool.php',
            app()->getAppPath() . 'lang/zh-cn/toolComment.php',
            app()->getAppPath() . 'lang/zh-cn/toolFavorite.php',
            app()->getAppPath() . 'lang/zh-cn/toolLike.php',
            app()->getAppPath() . 'lang/zh-cn/search.php',
            app()->getAppPath() . 'lang/zh-cn/comment.php',
            app()->getAppPath() . 'lang/zh-cn/commentLike.php',
            app()->getAppPath() . 'lang/zh-cn/favorite.php',
            app()->getAppPath() . 'lang/zh-cn/like.php',
            app()->getAppPath() . 'lang/zh-cn/post.php',
        ]
    ],
    // Accept-Language转义为对应语言包名称
    'accept_language' => [
        'zh-hans-cn' => 'zh-cn',
        'zh-cn' => 'zh-cn',
        'en' => 'en-us',
    ],
    // 是否支持语言分组
    'allow_group'     => true,

];
